services:
    edemy.background:
        class: eDemy\BackgroundBundle\Controller\BackgroundController
        calls:
            - [setEventDispatcher, ["@event_dispatcher"]]
        tags:
            - { name: kernel.event_subscriber }
